### PR TITLE
Patched for php7

### PR DESCRIPTION
**Pull request by Mikk3lRo**
Please make sure to create a new branch, this is NOT compatible with php5.x!

### CODE REVIEW

**Comment by Whissi** [comment]
Thank you for your contribution. I'll probably merge a slightly different version but that doesn't matter.

**Comment by Mikk3lRo** [comment]
I just needed it to work and to my surprise I succeeded in achieving that... Tested in production since about a week after php7 was released... But I don't actually know C, and I'm pretty sure my 5 lines ought to be 1, so no offense taken if you clean up a bit before merging ;)

**Comment by szepeviktor** [comment]
Closes #2

**Comment by Whissi** [comment]
Merged via d8f0304d9f8b72c55422991ff863ef60df3b9157.

**Pull request closed without merging**
